# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - CanvasSync

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Create EF Migration Bundle
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef migrations bundle --self-contained --force --project CanvasSync/CanvasSync.csproj -o "${{env.DOTNET_ROOT}}/myapp/efbundle.exe"

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7AE80EB7CBCC4A7F8547AE755CCBC3DA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A530B4FB7804FA69A9427C39C1EBD62 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF131621FFB9400D8021F354FFD166CE }}

      - name: Run Database Migrations
        shell: pwsh
        run: |
          # 1. Fetch the active database access token from Azure CLI
          $azureToken = az account get-access-token --resource "https://database.windows.net/" --query "accessToken" -o tsv
          
          # 2. Append the token to your connection string variable
          $fullConnectionString = "${{ secrets.AZURE_SQL_CONNECTION_STRING }}" + $azureToken
          
          # 3. Execute the migration bundle using the combined string
          ./efbundle.exe --connection "$fullConnectionString"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CanvasSync'
          slot-name: 'Production'
          package: .
          